### Pandas Indexing

1. Display Default and Set Column as Index

In [10]:
import pandas as pd

# Create DataFrame
df = pd.DataFrame({
    "school_code": ["s001", "s002", "s003", "s001", "s002", "s004"],
    "class": ["V", "V", "VI", "VI", "V", "VI"],
    "name": [
        "Alberto Franco",
        "Gino Mcneill",
        "Ryan Parkes",
        "Eesha Hinton",
        "Gino Mcneill",
        "David Parkes"
    ],
    "date_of_birth": [
        "15/05/2002",
        "17/05/2002",
        "16/02/1999",
        "25/09/1998",
        "11/05/2002",
        "15/09/1997"
    ],
    "age": [35, 32, 33, 30, 31, 32],
    "address": [
        "street1",
        "street2",
        "street3",
        "street1",
        "street2",
        "street4"
    ],
    "teacher_id": ["t1", "t2", "t3", "t4", "t5", "t6"]
})

print(df)

print("Set school_code as index")
print(df.set_index(df["school_code"]))

print("set name as index : ")
df.set_index(df["name"])

  school_code class            name date_of_birth  age  address teacher_id
0        s001     V  Alberto Franco    15/05/2002   35  street1         t1
1        s002     V    Gino Mcneill    17/05/2002   32  street2         t2
2        s003    VI     Ryan Parkes    16/02/1999   33  street3         t3
3        s001    VI    Eesha Hinton    25/09/1998   30  street1         t4
4        s002     V    Gino Mcneill    11/05/2002   31  street2         t5
5        s004    VI    David Parkes    15/09/1997   32  street4         t6
Set school_code as index
            school_code class            name date_of_birth  age  address  \
school_code
s001               s001     V  Alberto Franco    15/05/2002   35  street1
s002               s002     V    Gino Mcneill    17/05/2002   32  street2
s003               s003    VI     Ryan Parkes    16/02/1999   33  street3
s001               s001    VI    Eesha Hinton    25/09/1998   30  street1
s002               s002     V    Gino Mcneill    11/05/2002   31  street2
s004               s004    VI    David Parkes    15/09/1997   32  street4

            teacher_id
school_code
s001                t1
s002                t2
s003                t3
s001                t4
s002                t5
s004                t6
set name as index :

,school_code,class,name,date_of_birth,age,address,teacher_id
name,,,,,,,
Alberto Franco,s001,V,Alberto Franco,15/05/2002,35,street1,t1
Gino Mcneill,s002,V,Gino Mcneill,17/05/2002,32,street2,t2
Ryan Parkes,s003,VI,Ryan Parkes,16/02/1999,33,street3,t3
Eesha Hinton,s001,VI,Eesha Hinton,25/09/1998,30,street1,t4
Gino Mcneill,s002,V,Gino Mcneill,11/05/2002,31,street2,t5
David Parkes,s004,VI,David Parkes,15/09/1997,32,street4,t6

2. Create MultiIndex Frame

In [11]:
df.set_index([df["name"],df["age"]])

,,school_code,class,name,date_of_birth,age,address,teacher_id
name,age,,,,,,,
Alberto Franco,35,s001,V,Alberto Franco,15/05/2002,35,street1,t1
Gino Mcneill,32,s002,V,Gino Mcneill,17/05/2002,32,street2,t2
Ryan Parkes,33,s003,VI,Ryan Parkes,16/02/1999,33,street3,t3
Eesha Hinton,30,s001,VI,Eesha Hinton,25/09/1998,30,street1,t4
Gino Mcneill,31,s002,V,Gino Mcneill,11/05/2002,31,street2,t5
David Parkes,32,s004,VI,David Parkes,15/09/1997,32,street4,t6

3. Reset Index After Setting Column as Index

4. Create 64-bit Integer and Float Index Labels

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

5. DataFrame with Interval Index

In [14]:
import pandas as pd
print("Create an Interval Index using IntervalIndex.from_breaks:")
df_interval = pd.DataFrame({"X":[1, 2, 3, 4, 5, 6, 7]},
                            index = pd.IntervalIndex.from_breaks(
                            [0, 0.5, 1.0, 1.5, 2.0, 2.5, 3, 3.5]))    
print(df_interval)
print(df_interval.index)

print("\nCreate an Interval Index using IntervalIndex.from_tuples:")
df_interval = pd.DataFrame({"X":[1, 2, 3, 4, 5, 6, 7]},             
                            index = pd.IntervalIndex.from_tuples(
                            [(0, .5), (.5, 1), (1, 1.5), (1.5, 2), (2, 2.5), (2.5, 3), (3, 3.5)]))
print(df_interval)
print(df_interval.index)

print("\nCreate an Interval Index using IntervalIndex.from_arrays:")
df_interval = pd.DataFrame({"X":[1, 2, 3, 4, 5, 6, 7]},             
                            index = pd.IntervalIndex.from_arrays(
                            [0, .5, 1, 1.5, 2, 2.5, 3], [.5, 1, 1.5, 2, 2.5, 3, 3.5]))
print(df_interval)
print(df_interval.index)

Create an Interval Index using IntervalIndex.from_breaks:
            X
(0.0, 0.5]  1
(0.5, 1.0]  2
(1.0, 1.5]  3
(1.5, 2.0]  4
(2.0, 2.5]  5
(2.5, 3.0]  6
(3.0, 3.5]  7
IntervalIndex([(0.0, 0.5], (0.5, 1.0], (1.0, 1.5], (1.5, 2.0], (2.0, 2.5],
               (2.5, 3.0], (3.0, 3.5]],
              dtype='interval[float64, right]')

Create an Interval Index using IntervalIndex.from_tuples:
            X
(0.0, 0.5]  1
(0.5, 1.0]  2
(1.0, 1.5]  3
(1.5, 2.0]  4
(2.0, 2.5]  5
(2.5, 3.0]  6
(3.0, 3.5]  7
IntervalIndex([(0.0, 0.5], (0.5, 1.0], (1.0, 1.5], (1.5, 2.0], (2.0, 2.5],
               (2.5, 3.0], (3.0, 3.5]],
              dtype='interval[float64, right]')

Create an Interval Index using IntervalIndex.from_arrays:
            X
(0.0, 0.5]  1
(0.5, 1.0]  2
(1.0, 1.5]  3
(1.5, 2.0]  4
(2.0, 2.5]  5
(2.5, 3.0]  6
(3.0, 3.5]  7
IntervalIndex([(0.0, 0.5], (0.5, 1.0], (1.0, 1.5], (1.5, 2.0], (2.0, 2.5],
               (2.5, 3.0], (3.0, 3.5]],
              dtype='interval[float64, right]')

6. DataFrame Indexed by Date and Time